
# PurePerms by 64FF00 (xktiverz@gmail.com, @64ff00 for Twitter)

name: PurePerms
main: _64FF00\PurePerms\PurePerms
version: 1.4.2
api: [3.0.0]
load: POSTWORLD
author: "64FF00 & ProjectInfinity & translate by NativeDev"
website: https://github.com/PurePlugins/PurePerms
permissions:
  pperms:
    description: "PurePerms by 64FF00! (Twitter: @64FF00)"
    children:
      pperms.command:
        description: "Позволяет использовать все команды PurePerms."
        children:
          pperms.command.addgroup:
            description: "Позволяет добавить новую группу в список групп."
          pperms.command.addparent:
            description: "Позволяет добавить группу в другой список наследования групп."	
          pperms.command.defgroup:
            description: "Позволяет установить группу по умолчанию вручную."
          pperms.command.fperms:
            description: "Позволяет найти разрешения для конкретного плагина."
          pperms.command.groups:
            description: "Позволяет увидеть список всех групп."
          pperms.command.listgperms:
            description: "Позволяет просмотреть список всех разрешений из группы."
          pperms.command.listuperms:
            description: "Позволяет увидеть список всех разрешений пользователя."
          pperms.command.ppinfo:
            default: true
            description: "Позволяет получить текущую информацию о PurePerms."
          pperms.command.ppreload:
            description: "Позволяет перезагрузить все конфигурации PurePerms."
          pperms.command.rmgroup:
            description: "Позволяет удалить группу из списка групп."
          pperms.command.rmparent:
            description: "Позволяет удалить группу из другого списка наследования групп."		
          pperms.command.setgperm:
            description: "Позволяет добавить разрешение в группу."
          pperms.command.setgroup:
            description: "Позволяет установить группу для пользователя."
          pperms.command.setuperm:
            description: "Позволяет добавить разрешение пользователю."
          pperms.command.unsetgperm:
            description: "Позволяет удалить разрешение из группы."
          pperms.command.unsetuperm:
            description: "Позволяет удалить разрешение у пользователя."
          pperms.command.usrinfo:
            description: "Позволяет просматривать информацию о пользователе."
      pperms.noeul:
        description: "Позволяет получить доступ ко всем функциям, связанным с Noeul."
        children:
          pperms.noeul.ppsudo:
            description: "Позволяет использовать команду Noel 'pseudo'."
